name: permeator-probe-env
channels:
  - conda-forge
  - defaults
dependencies:
# TODO: add OpenFoam dependencies
  - sphinx-tags
  - matplotlib
  - meshio[all]
  - pip>=20.1
  - ipykernel
  - nbconvert
  - fenics-dolfinx
  - festim=2.0a7
  - python-gmsh
  - pip:
    - pyparsing
    - h-transport-materials==0.16
    - pyvista[all,trame]  # trame cannot be installed on conda
    - git+https://github.com/festim-dev/foam2dolfinx